services:
  demakai-bot:
    build: .
    container_name: demakai-bot
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    restart: unless-stopped
    networks:
      - demakai-prod-net
    volumes:
      - ./wa-session-prod:/app/wa-session-prod  

networks:
  demakai-prod-net:
    driver: bridge

