version: "3.9"
services:
  demakai-bot-dev:
    build: .
    container_name: demakai-bot-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - demakai-net
    volumes:
      - .:/app

networks:
  demakai-net:
    driver: bridge
