version: "3.9"
services:
  demakai-bot-dev:
    build: .
    container_name: demakai-bot-dev
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      - BOT_MODE=dev
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      - demakai-net

networks:
  demakai-net:
    driver: bridge
