services:
  demakai-bot:
    build: .
    container_name: demakai-bot
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
      - WEBHOOK_BASE_URL=http://10.133.21.24:3001
    restart: unless-stopped
    networks:
      - demakai-prod-net
