services:
  demakai-bot:
    build: .
    container_name: demakai-bot
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    restart: unless-stopped
    networks:
      - demakai-prod-net
    volumes:
      - ./wa-session-prod:/app/wa-session-prod
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

networks:
  demakai-prod-net:
    driver: bridge