version: "3.9"
services:
  demakai-bot:
    build: .
    container_name: demakai-bot
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
    networks:
      - demakai-prod-net

networks:
  demakai-prod-net:
    driver: bridge
