version: "3.9"
services:
  demakai-bot:
    build: .
    container_name: demakai-bot
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - BOT_MODE=Production
    restart: always
    volumes:
      - .:/app
    networks:
      - demakai-net

networks:
  demakai-net:
    driver: bridge
